version: '3'

services:
  ticket-plug:
    restart: unless-stopped
    depends_on:
      - db
      - redis
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    command: sh -c "sh server.sh"
    volumes:
      - ./:/app
  db:
    image: postgres:15.2-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgresdb:/var/lib/postgresql/data

  worker:
    restart: unless-stopped
    depends_on:
      - redis
    build: .
    command: sh -c "sh worker.sh"

  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data

volumes:
  postgresdb:
  redisdata:
