version: '3'
services:
  ticket-plug:
    restart: unless-stopped
    depends_on:
      - db 
      - celery
    build: .
    ports:
      - 8000:8000
    command: sh -c "sh server.sh"
    volumes:
      - ./:/app
    env_file:
      - ./.env
  celery:
    restart: unless-stopped
    depends_on:
      - redis
    build: .
    command: sh -c "sh worker.sh"
    env_file:
      - ./.env
  db:
    image: postgres:15.2-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgresdb:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

volumes:
  postgresdb:
  redisdata:
